import { useState, useRef, useEffect } from "react";
import { useParams, useLocation, useSearch } from "wouter";
import { useQuery, useMutation } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";
import { Skeleton } from "@/components/ui/skeleton";
import { Checkbox } from "@/components/ui/checkbox";
import { apiRequest } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import { useAuth } from "@/lib/auth";
import { ArrowLeft, FileSignature, Fingerprint, CheckCircle2, Loader2, ArrowRight, ScrollText } from "lucide-react";
import type { Strategy, Plan, User } from "@shared/schema";
import { Link } from "wouter";

const AGREEMENT_TEXT = `Investment Advisor and Research Analyst Services Agreement

THIS DOCUMENT IS AN ELECTRONIC RECORD IN TERMS OF THE INFORMATION TECHNOLOGY ACT, 2000 AND RULES MADE THEREUNDER AS APPLICABLE AND THE AMENDED PROVISIONS PERTAINING TO ELECTRONIC RECORDS IN VARIOUS STATUTES AS AMENDED BY THE INFORMATION TECHNOLOGY ACT, 2000. THIS ELECTRONIC RECORD IS GENERATED BY A COMPUTER SYSTEM AND DOES NOT REQUIRE ANY PHYSICAL OR DIGITAL SIGNATURES.

THIS DOCUMENT IS PUBLISHED IN ACCORDANCE WITH THE PROVISIONS OF RULE 3 (1) OF THE INFORMATION TECHNOLOGY (INTERMEDIARIES GUIDELINES) RULES, 2011 THAT REQUIRE PUBLISHING THE RULES AND REGULATIONS, PRIVACY POLICY, AND TERMS OF USE FOR ACCESS OR USAGE OF THE "PLATFORM" (DEFINED BELOW).

The online platform \u2013 www.thealphamarket.com ("Website"), and the iOS and Android mobile applications \u2013 "AlphaMarket" ("App") is owned and operated by Edhaz Financial Services Private Limited, a private limited company incorporated under the Companies Act, 2013 with its registered office at [Your Office Address] ("Edhaz"). The App and the Website, its sub-domains, and other sites/apps/other channels maintained by Edhaz to enable distribution of financial products and services shall be collectively referred to hereinafter as the ("Platform"). Edhaz is not a SEBI registered Investment Advisor and Research Analyst but provides a marketplace for SEBI Registered Investment Advisor and Research Analysts and Research Analysts to publish their strategies.

Edhaz requests you to carefully go through and accept this Investment Advisor and Research Analyst Services Agreement ("Agreement") to avail the advisory services provided by SEBI Registered Investment Advisor and Research Analysts or Research Analysts through the Platform. If you continue to browse and use this Platform, you irrevocably and unconditionally agree to comply with, abide by, and be bound by all the obligations as stipulated under this Agreement, which, together with our privacy policy and any other applicable policies which are incorporated herein by way of reference or available by hyperlink on the Website, shall govern Edhaz's relationship with you in relation to this Platform.

Part A: Client Consent

I/We ("Client") have read and understood the terms and conditions of the Investment Advisor and Research Analyst Services Agreement facilitated by Edhaz Financial Services Private Limited ("Edhaz") through its Marketplace Platform, The AlphaMarket. This agreement, including the fee structure and the mechanism for charging and payment of fees, is a standardized structure decided and agreed upon between the Client and the SEBI Registered Investment Advisor and Research Analyst ("RIA") or Research Analyst ("RA") connected via The AlphaMarket platform. Edhaz provides the platform to facilitate this connection, while all advisory services and fee arrangements are directly between the Client and the RIA or RA.

Part B: Declaration of Investment Advisor and Research Analyst

The Client, by agreeing to this electronic and digital agreement, signifies consent by checking the box and clicking the "I agree" button at the bottom of this Agreement. Upon doing so, the Client must then pay the subscription fees for the selected strategy provided by the SEBI Registered Investment Advisor and Research Analyst ("RIA") or Research Analyst ("RA"). The advisory relationship between the Client and the Advisor will commence only after the successful payment of the strategy's subscription fees and the completion of the Client's eKYC and Risk Profiling.

Part C: Fees Specified as per SEBI (Investment Advisor and Research Analysts) Regulations, 2013 and Relevant Circulars

In the case of AlphaMarket, a Marketplace platform by Edhaz Financial Services Private Limited, the Client pays the subscription fees for the specific strategy offered by the SEBI Registered Investment Advisor and Research Analyst ("RIA") or Research Analyst ("RA") that they choose to subscribe to. The fees are determined by the Advisor and are based on the duration of the subscription.

1. DEFINITIONS AND INTERPRETATION

Unless the context otherwise requires, the capitalized terms set out herein shall have the following meanings:

\u2022 "Agreement" means this Investment Advisor and Research Analyst Services Agreement along with the schedules and annexures attached hereto.
\u2022 "Applicable Laws" shall mean the laws, including but not limited to any enactment, legislation, subordinate legislation, rules, regulations, circulars, statutory guidelines, notifications, policies applicable in India.
\u2022 "Assets under Advice (AUA)" means the aggregate net asset value of securities and investment products for which the Investment Advisor and Research Analyst has rendered services.
\u2022 "Investment" shall mean the investment made by the Client in Securities, based on the advice received from the Investment Advisor and Research Analyst.
\u2022 "SEBI" shall mean the Securities and Exchange Board of India.

2. APPOINTMENT OF THE INVESTMENT ADVISOR AND RESEARCH ANALYST

In accordance with applicable laws, the Client, at their own discretion and risk, engages with SEBI Registered Investment Advisors (RIAs) and Research Analysts (RAs) through The AlphaMarket, a marketplace product of Edhaz Financial Services Private Limited. The advice provided by the RIAs and RAs will be akin to a model portfolio or generic in nature, and the discretion to execute the advice lies solely with the Client.

3. SCOPE OF INVESTMENT ADVISOR AND RESEARCH ANALYST SERVICES

Through The AlphaMarket, SEBI Registered Investment Advisors (RIAs) and Research Analysts (RAs) provide advice related to investing in, purchasing, selling, or otherwise dealing in stocks for the benefit of the Client. The RIAs and RAs shall act in a fiduciary capacity toward the Client at all times.

4. RISK FACTORS, RISK PROFILING, AND ASSESSMENT

The Client agrees to comply with all procedures required by the SEBI Registered Investment Advisors (RIAs) and Research Analysts (RAs) on The AlphaMarket platform for conducting risk assessments and profiling as mandated by Applicable Laws.

5. OBLIGATIONS AND REPRESENTATIONS OF THE INVESTMENT ADVISOR AND RESEARCH ANALYST

\u2022 The RIA and RA agree to uphold high standards of integrity and fairness in all interactions with the Client.
\u2022 The RIA and RA represent and warrant that they will ensure continuous compliance with the eligibility criteria specified under the SEBI (Investment Advisers) Regulations, 2013.
\u2022 The RIA and RA will provide reports to clients regarding potential and current investments.
\u2022 The RIA and RA will maintain all required records as per Applicable Laws.
\u2022 The RIA and RA will conduct periodic audits as required under Applicable Law.
\u2022 The RIA and RA will adhere to the code of conduct as specified in the Third Schedule to the SEBI (Investment Adviser) Regulations, 2013.

6. OBLIGATIONS OF THE CLIENT

\u2022 Keep the RIA and RA duly informed of any changes in constitution, identity, investment objectives, risk profile, or any other relevant information.
\u2022 Execute any documents as may be required by the RIA and RA to enable them to render their services.
\u2022 Be solely responsible for compliance with all applicable laws and regulations.
\u2022 Make timely payment of the fees due to the RIA and RA for the strategies subscribed to on The AlphaMarket Platform.

7. REPRESENTATIONS AND WARRANTIES OF THE PARTIES

The Parties each represent and warrant that they have full power, capacity, and authority to execute, deliver, and perform this Agreement. This Agreement has been duly executed and constitutes legal, valid, and binding obligations on the Parties.

8. DISCLAIMERS

\u2022 The Client acknowledges that the Investment Advisory Services are intended solely as advisory.
\u2022 The AlphaMarket, its Investment Advisors, and Research Analysts shall not be liable for any losses incurred by the Client due to fluctuations in asset values.
\u2022 The AlphaMarket shall not be liable for any direct or indirect losses or damages resulting from the advisory services provided.

9. PERIOD OF AGREEMENT & TERMINATION

\u2022 This Agreement shall commence on the date the Client subscribes to their chosen strategy and will remain in effect until the end of the subscription period.
\u2022 Either party may terminate this Agreement by providing at least 30 days' written notice.
\u2022 Immediate termination is permissible if the Client fails to pay fees, provides inaccurate information, or is prohibited from accessing financial markets.

10. FEES & BILLING

The AlphaMarket does not charge separate fees to clients. Clients subscribing to a particular strategy pay the subscription fees associated with that strategy. Different strategies may have different fees, which are determined at the discretion of the RIAs and RAs.

11. CONFIDENTIALITY

The Client agrees to treat all information pertaining to The AlphaMarket and its Advisors as confidential. The AlphaMarket will also uphold the confidentiality of all personal data provided by the Client.

12. PERSONAL DATA

The AlphaMarket may collect and utilize personal data to deliver services and generate reports. The Client agrees to provide the necessary data and consents to the use and sharing of their personal data as required by law.

13. RECORDING OF COMMUNICATIONS AND CONSENT TO RECEIVE MESSAGES

Conversations may be recorded for quality control and dispute resolution. The Client explicitly agrees to receive communications from The AlphaMarket Platform including promotional, transactional, and marketing messages.

14. ASSIGNMENT AND TRANSITION

The Client may not assign their rights or obligations without prior written consent. The AlphaMarket may assign their rights or obligations to a successor or affiliate.

15. AMENDMENT

Amendments to this Agreement require mutual written consent.

16. INDEMNITY AND LIMITATION OF LIABILITY

The Client agrees to indemnify and hold harmless The AlphaMarket against any claims or losses arising from breaches of this Agreement by the Client.

17. INVALIDITY

If any provision is deemed illegal or unenforceable, the remaining provisions shall continue to be valid.

18. NO WAIVER

Failure to enforce any provision shall not constitute a waiver of that provision or any other rights.

19. GRIEVANCE AND DISPUTE SETTLEMENT

Client grievances should be directed to hello@thealphamarket.com. Disputes will first be attempted to be resolved through mutual consultation, and if unresolved, referred to arbitration in accordance with the Arbitration and Conciliation Act, 1996 in Bangalore.

20. GOVERNING LAW

This Agreement shall be governed by Indian laws, with exclusive jurisdiction in Bangalore, Karnataka.

21. SEVERABILITY

If any provision is invalid, the remaining provisions shall remain effective.

22. FORCE MAJEURE

The Investment Advisor and Research Analyst shall not be liable for delays due to circumstances beyond its control.

23. ENTIRETY

This Agreement constitutes the entire agreement between the parties regarding the Advisory Services.

24. RELATIONSHIP

This Agreement establishes a client-advisor relationship. It does not create a partnership, joint venture, or agency relationship.

Annexure B: Risk Statements

\u2022 The Client acknowledges the risks associated with investments in Securities, equity-linked investments, real estate, derivatives trading, and mutual funds.
\u2022 Direct and indirect investments in the Indian capital market are subject to risks associated with equity-linked investments.
\u2022 Investments in derivatives trading involve considerable risk, which may lead to significant losses potentially exceeding the capital invested.
\u2022 The Client agrees that while The AlphaMarket strives to provide accurate and timely information and advice, it does not assume responsibility for errors or omissions.

BY CLICKING THE "AGREE" OR "SUBMIT" BUTTON BELOW, THE CLIENT CONSENTS TO AND AGREES TO ABIDE BY ALL TERMS AND CONDITIONS OF THIS INVESTMENT ADVISOR AND RESEARCH ANALYST SERVICES AGREEMENT. THIS AGREEMENT IS ELECTRONICALLY EXECUTED. THE DATE OF THIS AGREEMENT SHALL BE THE DATE ON WHICH THE CLIENT PAYS THE SUBSCRIPTION FEES FOR THE STRATEGY THEY HAVE SUBSCRIBED TO.`;

export default function EsignAgreementPage() {
  const { id } = useParams<{ id: string }>();
  const [, navigate] = useLocation();
  const searchString = useSearch();
  const params = new URLSearchParams(searchString);
  const planId = params.get("plan");
  const { user } = useAuth();
  const { toast } = useToast();

  const [step, setStep] = useState<"read" | "sign" | "done">("read");
  const [hasScrolledToBottom, setHasScrolledToBottom] = useState(false);
  const [agreedToTerms, setAgreedToTerms] = useState(false);
  const [aadhaarNumber, setAadhaarNumber] = useState("");
  const [otp, setOtp] = useState("");
  const [referenceId, setReferenceId] = useState<number | null>(null);
  const [otpSent, setOtpSent] = useState(false);
  const [signedName, setSignedName] = useState<string | null>(null);

  const scrollRef = useRef<HTMLDivElement>(null);

  const { data: strategy, isLoading: strategyLoading } = useQuery<Strategy & { advisor?: User }>({
    queryKey: ["/api/strategies", id],
  });

  const { data: plans } = useQuery<Plan[]>({
    queryKey: ["/api/strategies", id, "plans"],
    enabled: !!id,
  });

  const { data: esignStatus } = useQuery<{ signed: boolean; agreementId?: string; signedAt?: string; aadhaarName?: string }>({
    queryKey: ["/api/esign/status", id, planId],
    queryFn: async () => {
      const res = await fetch(`/api/esign/status?strategyId=${id}&planId=${planId}`, { credentials: "include" });
      if (!res.ok) throw new Error("Failed to check eSign status");
      return res.json();
    },
    enabled: !!id && !!planId && !!user,
  });

  useEffect(() => {
    if (esignStatus?.signed) {
      setStep("done");
      setSignedName(esignStatus.aadhaarName || null);
    }
  }, [esignStatus]);

  const handleScroll = () => {
    if (scrollRef.current) {
      const { scrollTop, scrollHeight, clientHeight } = scrollRef.current;
      if (scrollTop + clientHeight >= scrollHeight - 50) {
        setHasScrolledToBottom(true);
      }
    }
  };

  const sendOtpMutation = useMutation({
    mutationFn: async () => {
      const res = await apiRequest("POST", "/api/esign/otp", {
        strategyId: id,
        planId,
        aadhaarNumber,
      });
      return res.json();
    },
    onSuccess: (data) => {
      setReferenceId(data.referenceId);
      setOtpSent(true);
      toast({ title: "OTP Sent", description: "Please check your Aadhaar-linked mobile for the OTP." });
    },
    onError: (err: Error) => {
      toast({ title: "Error", description: err.message, variant: "destructive" });
    },
  });

  const verifyOtpMutation = useMutation({
    mutationFn: async () => {
      const res = await apiRequest("POST", "/api/esign/verify", {
        strategyId: id,
        planId,
        referenceId,
        otp,
      });
      return res.json();
    },
    onSuccess: (data) => {
      setStep("done");
      setSignedName(data.name);
      toast({ title: "Agreement Signed", description: "Your agreement has been successfully e-signed." });
    },
    onError: (err: Error) => {
      toast({ title: "Verification Failed", description: err.message, variant: "destructive" });
    },
  });

  const selectedPlan = plans?.find(p => p.id === planId);
  const advisorName = strategy?.advisor?.companyName || strategy?.advisor?.username || "Advisor";

  if (strategyLoading) {
    return (
      <div className="min-h-screen bg-background">
        <Navbar />
        <div className="max-w-4xl mx-auto px-4 md:px-6 py-8 space-y-6">
          <Skeleton className="h-8 w-60" />
          <Skeleton className="h-[400px]" />
        </div>
      </div>
    );
  }

  if (!strategy || !planId) return null;

  return (
    <div className="min-h-screen bg-background flex flex-col">
      <Navbar />
      <div className="flex-1 max-w-4xl mx-auto px-4 md:px-6 py-8 w-full space-y-6">
        <div>
          <Link href={`/strategies/${id}/subscribe`}>
            <Button variant="ghost" size="sm" className="mb-3" data-testid="button-back-subscribe">
              <ArrowLeft className="w-4 h-4 mr-1" />
              Back to Plans
            </Button>
          </Link>
          <h1 className="text-2xl font-bold flex items-center gap-2" data-testid="text-esign-title">
            <FileSignature className="w-6 h-6" />
            Investment Advisory Services Agreement
          </h1>
          <p className="text-sm text-muted-foreground mt-1">
            by {advisorName} &middot; Strategy: {strategy.name}
            {selectedPlan && <> &middot; Plan: {selectedPlan.name}</>}
          </p>
        </div>

        <div className="flex items-center gap-3 text-sm">
          <div className={`flex items-center gap-1.5 ${step === "read" ? "text-primary font-medium" : step !== "read" ? "text-muted-foreground" : ""}`}>
            <div className={`w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold ${step === "read" ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground"}`}>1</div>
            <span>Read Agreement</span>
          </div>
          <div className="h-px flex-1 bg-border" />
          <div className={`flex items-center gap-1.5 ${step === "sign" ? "text-primary font-medium" : step === "done" ? "text-muted-foreground" : "text-muted-foreground"}`}>
            <div className={`w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold ${step === "sign" ? "bg-primary text-primary-foreground" : step === "done" ? "bg-accent text-accent-foreground" : "bg-muted text-muted-foreground"}`}>2</div>
            <span>eSign with Aadhaar</span>
          </div>
          <div className="h-px flex-1 bg-border" />
          <div className={`flex items-center gap-1.5 ${step === "done" ? "text-accent font-medium" : "text-muted-foreground"}`}>
            <div className={`w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold ${step === "done" ? "bg-accent text-accent-foreground" : "bg-muted text-muted-foreground"}`}>3</div>
            <span>Proceed to Payment</span>
          </div>
        </div>

        {step === "read" && (
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-base flex items-center gap-2">
                <ScrollText className="w-4 h-4" />
                Please read the agreement carefully
              </CardTitle>
              <p className="text-xs text-muted-foreground">Scroll to the bottom to enable the consent checkbox</p>
            </CardHeader>
            <CardContent className="space-y-4">
              <div
                ref={scrollRef}
                onScroll={handleScroll}
                className="h-[400px] overflow-y-auto border rounded-md p-4 text-sm leading-relaxed whitespace-pre-wrap bg-muted/30"
                data-testid="div-agreement-text"
              >
                {AGREEMENT_TEXT}
              </div>

              <div className="flex items-start gap-2 pt-2">
                <Checkbox
                  id="agree"
                  checked={agreedToTerms}
                  onCheckedChange={(checked) => setAgreedToTerms(checked === true)}
                  disabled={!hasScrolledToBottom}
                  data-testid="checkbox-agree-terms"
                />
                <label
                  htmlFor="agree"
                  className={`text-sm leading-tight cursor-pointer ${!hasScrolledToBottom ? "text-muted-foreground" : ""}`}
                >
                  I have read and understood the Investment Advisor and Research Analyst Services Agreement. I agree to abide by all terms and conditions.
                </label>
              </div>

              <div className="flex justify-end pt-2">
                <Button
                  onClick={() => setStep("sign")}
                  disabled={!agreedToTerms}
                  data-testid="button-proceed-esign"
                >
                  Proceed to eSign
                  <ArrowRight className="w-4 h-4 ml-1" />
                </Button>
              </div>
            </CardContent>
          </Card>
        )}

        {step === "sign" && (
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-base flex items-center gap-2">
                <Fingerprint className="w-4 h-4" />
                eSign Agreement with Aadhaar OTP
              </CardTitle>
              <p className="text-xs text-muted-foreground">
                Verify your identity using Aadhaar OTP to electronically sign this agreement
              </p>
            </CardHeader>
            <CardContent className="space-y-4">
              {!otpSent ? (
                <div className="space-y-3 max-w-md">
                  <div className="space-y-1.5">
                    <Label htmlFor="aadhaar">Aadhaar Number</Label>
                    <Input
                      id="aadhaar"
                      placeholder="Enter 12-digit Aadhaar number"
                      value={aadhaarNumber}
                      onChange={(e) => setAadhaarNumber(e.target.value.replace(/\D/g, "").slice(0, 12))}
                      maxLength={12}
                      data-testid="input-aadhaar-esign"
                    />
                    <p className="text-xs text-muted-foreground">An OTP will be sent to your Aadhaar-linked mobile number</p>
                  </div>
                  <Button
                    onClick={() => sendOtpMutation.mutate()}
                    disabled={aadhaarNumber.length !== 12 || sendOtpMutation.isPending}
                    data-testid="button-send-otp-esign"
                  >
                    {sendOtpMutation.isPending ? <Loader2 className="w-4 h-4 mr-1 animate-spin" /> : <Fingerprint className="w-4 h-4 mr-1" />}
                    Send OTP
                  </Button>
                </div>
              ) : (
                <div className="space-y-3 max-w-md">
                  <Badge variant="outline">OTP sent to Aadhaar-linked mobile</Badge>
                  <div className="space-y-1.5">
                    <Label htmlFor="otp">Enter OTP</Label>
                    <Input
                      id="otp"
                      placeholder="Enter 6-digit OTP"
                      value={otp}
                      onChange={(e) => setOtp(e.target.value.replace(/\D/g, "").slice(0, 6))}
                      maxLength={6}
                      data-testid="input-otp-esign"
                    />
                  </div>
                  <div className="flex gap-2">
                    <Button
                      onClick={() => verifyOtpMutation.mutate()}
                      disabled={otp.length !== 6 || verifyOtpMutation.isPending}
                      data-testid="button-verify-otp-esign"
                    >
                      {verifyOtpMutation.isPending ? <Loader2 className="w-4 h-4 mr-1 animate-spin" /> : <CheckCircle2 className="w-4 h-4 mr-1" />}
                      Verify & Sign
                    </Button>
                    <Button
                      variant="outline"
                      onClick={() => {
                        setOtpSent(false);
                        setOtp("");
                        setReferenceId(null);
                      }}
                      data-testid="button-resend-otp-esign"
                    >
                      Resend OTP
                    </Button>
                  </div>
                </div>
              )}
            </CardContent>
          </Card>
        )}

        {step === "done" && (
          <Card>
            <CardContent className="py-8 text-center space-y-4">
              <div className="w-16 h-16 rounded-full bg-accent/20 flex items-center justify-center mx-auto">
                <CheckCircle2 className="w-8 h-8 text-accent" />
              </div>
              <div>
                <h3 className="text-lg font-semibold" data-testid="text-esign-success">Agreement Successfully Signed</h3>
                <p className="text-sm text-muted-foreground mt-1">
                  Signed by: <span className="font-medium text-foreground">{signedName || "Verified"}</span>
                </p>
                <p className="text-xs text-muted-foreground mt-1">
                  A copy of this agreement has been sent to your registered email and the advisor's email.
                </p>
              </div>
              <Button
                onClick={() => navigate(`/strategies/${id}/payment?plan=${planId}`)}
                data-testid="button-proceed-payment-after-esign"
              >
                Proceed to Payment
                <ArrowRight className="w-4 h-4 ml-1" />
              </Button>
            </CardContent>
          </Card>
        )}
      </div>
      <Footer />
    </div>
  );
}
