"""
AlphaForge — Instrument Service
Static fallback instrument list when Groww API is unavailable.
This includes Nifty 500 symbols for simulation mode.
"""

NIFTY500_SYMBOLS = [
    "RELIANCE","TCS","HDFCBANK","INFY","ICICIBANK","HINDUNILVR","SBIN","BAJFINANCE",
    "BHARTIARTL","KOTAKBANK","LT","ASIANPAINT","AXISBANK","MARUTI","TITAN","SUNPHARMA",
    "ULTRACEMCO","HCLTECH","WIPRO","NESTLEIND","TECHM","POWERGRID","NTPC","TATASTEEL",
    "JSWSTEEL","COALINDIA","ADANIENT","ADANIPORTS","HINDALCO","TATAMOTORS","LTIM",
    "BAJAJFINSV","DRREDDY","DIVISLAB","CIPLA","BPCL","ONGC","GRASIM","INDUSINDBK",
    "M&M","EICHERMOT","BAJAJ-AUTO","HEROMOTOCO","TATACONSUM","BRITANNIA","APOLLOHOSP",
    "HDFCLIFE","SBILIFE","PIDILITIND","SIEMENS","ABB","HAVELLS","VOLTAS","WHIRLPOOL",
    "BERGEPAINT","KANSAINER","SUPREMEIND","AUROPHARMA","TORNTPHARM","ALKEM","LUPIN",
    "BIOCON","IPCALAB","CADILAHC","NATCOPHARM","GRANULES","LAURUSLABS","GLAND","IPCA",
    "BANDHANBNK","FEDERALBNK","IDFCFIRSTB","PNB","BANKBARODA","CANBK","UNIONBANK",
    "INDIANB","UCOBANK","CENTRALBK","IOB","MAHABANK","PUNJABND","SYNDIBANK",
    "CHOLAFIN","MANAPPURAM","MUTHOOTFIN","LICHSGFIN","PNBHOUSING","CANFINHOME",
    "GRUH","REPCO","AAVAS","APTUS","HOMEFIRST","SATIN","AROHAN",
    "JUBLFOOD","DEVYANI","RESTAURANT","WESTLIFE","BARBEQUE","SAPPHIREFDS",
    "DMART","TRENT","ABFRL","SHOPERSTOP","VBL","RADICO","GLOBUSSPR",
    "PAGEIND","DOLLAR","RUPA","NIIT","NETWORK18","TV18BRDCST","SUNTV",
    "ZEEL","PVR","INOX","NAZARA","DELTACORP","PAISALO","CREDITMID",
    "ITC","GODREJCP","MARICO","COLPAL","DABUR","PGHH","GILLETTE",
    "EMAMILTD","JYOTHYLAB","BAJAJCON","HATSUN","HERITAGE","VADILALIND",
    "IRCTC","INDIGO","SPICEJET","BLUEDART","CONCOR","GATI","MAHLOG",
    "ADANIGREEN","TATAPOWER","TORNTPOWER","CESC","JSPL","NLCINDIA","NHPC",
    "RECLTD","PFC","IRFC","NABARD","SIDBI",
    "DLF","GODREJPROP","PRESTIGE","BRIGADE","SOBHA","MAHINDCIE","KOLTEPATIL",
    "PHOENIXLTD","NESCO","INDIABULLS","EMBASSY","BROOKFIELD","NEXUSMALLS",
    "MPHASIS","PERSISTENT","COFORGE","KPIT","SONATSOFTW","MASTEK","ZENSAR",
    "HEXAWARE","CYIENT","NIITTECH","TATAELXSI","SASKEN","INFOBEANTEC",
    "POLYCAB","VGUARD","FINOLEX","HMVL","KEI","RRKABEL","STERLITE",
    "AMBER","DIXON","VOLTAS","BLUE STAR","CARRIER","DAIKIN","HITACHIENRG",
    "CGPOWER","BHEL","BEL","HAL","BEML","GRSE","MAZAGON","COCHINSHIP",
    "GAIL","MGL","IGL","GSPL","PETRONET","IOC","MRPL","CPCL","NRL",
    "VEDL","HINDZINC","NALCO","NMDC","MOIL","GMRINFRA","IRB","NHAI",
    "ZOMATO","NYKAA","PAYTM","POLICYBZR","CARTRADE","EASEMYTRIP",
    "HDFCAMC","NIPPONLIFE","UTIMF","MIRAEASSET","AXIS AMC","SBICARD",
    "CHOLAHLDNG","ICICIGI","NIACL","ORIENTINS","STARHEALTH","GICRE",
]

FALLBACK_INSTRUMENTS = [
    {"symbol": sym, "name": sym, "exchange": "NSE", "segment": "CASH",
     "instrument_key": f"NSE_EQ|{sym}", "isin": "", "lot_size": 1,
     "tick_size": 0.05, "token": str(i)}
    for i, sym in enumerate(NIFTY500_SYMBOLS)
]
